# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# カラースキーム
[[plugins]]
repo = 'sjl/badwolf'

# denite.vim
[[plugins]]
repo = 'Shougo/denite.nvim'

# ディレクトリ構造をtree形式で表示
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

# vimで便利にgitを使うためのやつ
# 個人的には、行の色が変わってほしい
[[plugins]]
repo = 'airblade/vim-gitgutter'

# インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# markdow用の基礎repo
[[plugins]]
repo='godlygeek/tabular'

# markdown形式ファイルで読み込む
[[plugins]]
repo  = 'gabrielelana/vim-markdown'
# on_ft = 'markdown'

# 行末の不要な空白を可視化&削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# vimdocを日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# syntax checker
[[plugins]]
repo = 'dense-analysis/ale'

# vim-lsp
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
