# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]
# Lazy load
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Github plugins
## Highlight command
[plugins.F-Sy-H]
github = "z-shell/F-Sy-H"
apply = ["defer"]

## Auto suggest command
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
use = ["{{ name }}.zsh"]

## More Better Completions
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

## Git prompt with right side
[plugins.git-prompt]
github = "woefe/git-prompt.zsh"
apply = ["defer"]

[plugins.fzf]
github = "junegunn/fzf"
# apply = ['fzf-install', 'fzf-source']

# Local plugins
## Custom commands
[plugins.usability]
local = "~/.config/zsh"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zkbd]
local = "~/.config/zsh"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[templates]
# Settings of lazy-load
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
fzf-install = "{{ dir }}/install --bin > /dev/null \n[[ ! $PATH =~ {{ dir }} ]] && export PATH=\"$PATH:{{ dir }}/bin\"\n"
fzf-source = "{% for file in files %}source \"{{ file }}\"\n{% endfor %}"
