import = [
	"/Users/hosoi/.config/alacritty/font-config.toml",
	"/Users/hosoi/.config/alacritty/local.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#000000"
bright_foreground = "#eeeeee"
foreground = "#acb4c2"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.75"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = '\'
key = "_"

[[keyboard.bindings]]
chars = "_"
key = "_"
mods = "Shift"

[[keyboard.bindings]]
chars = '\'
key = "¥"

[[keyboard.bindings]]
chars = "¥"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Minus"
mods = "Command|Shift"

[window]
decorations = "full"
opacity = 0.8
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
